version: '2'
services:
  jenkins:
    build:
      dockerfile: Dockerfile-jenkins
      context: .
    ports:
      - 8081:8080
      - 5000:5000
    volumes:
      - ./jenkins:/var/jenkins_home/
  server:
    build:
      dockerfile: Dockerfile-server
      context: .
    ports:
      - 8082:8000
    volumes:
      - ./server:/source/server
